import { GoogleGenAI } from "@google/genai";

// 👉 Đặt biến này trong Vercel: GEMINI_API_KEY
// Project Settings → Environment Variables → KEY = GEMINI_API_KEY, VALUE = <api key của bạn>
const apiKey = process.env.GEMINI_API_KEY;

if (!apiKey) {
  throw new Error(
    "Thiếu GEMINI_API_KEY. Hãy cấu hình trong Vercel Project Settings → Environment Variables."
  );
}

// File này phải chạy ở môi trường server (API route / serverless function),
// không import trực tiếp vào component client để tránh lộ key.
const ai = new GoogleGenAI({ apiKey });

/**
 * Edits an image using Gemini 2.5 Flash Image ("Nano Banana").
 */
export const editImageWithGemini = async (
  base64Image: string, 
  prompt: string, 
  mimeType: string = 'image/png'
): Promise<string> => {
  try {
    const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { inlineData: { data: cleanBase64, mimeType: mimeType } },
          { text: prompt },
        ],
      },
    });

    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        }
      }
    }
    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

/**
 * Generates a Meme based on caption or template description.
 * Can be used with or without a source image.
 */
export const generateMeme = async (
  prompt: string,
  style: string,
  base64Image?: string
): Promise<string> => {
  try {
    const finalPrompt = `Create a meme image. Caption: "${prompt}". Style: ${style}. ensure the text is legible and funny.`;
    
    const parts: any[] = [{ text: finalPrompt }];

    if (base64Image) {
      const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
      parts.unshift({ inlineData: { data: cleanBase64, mimeType: 'image/png' } });
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts },
    });

    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        }
      }
    }
    throw new Error("Meme generation failed.");
  } catch (error) {
    console.error("Meme Gen Error:", error);
    throw error;
  }
};

/**
 * Generates a Notion-style Personal Profile (HTML code).
 */
export const generateNotionProfile = async (userInfo: string): Promise<string> => {
  try {
    const prompt = `
      Create a single-file HTML (with embedded Tailwind CSS via CDN) for a Personal Profile Page in the style of "Notion" (Minimalist, emoji icons, clean typography, whitespace).
      
      User Information:
      ${userInfo}
      
      Requirements:
      - Use a Notion-like font stack (Inter, sans-serif).
      - Include a cover image placeholder (use unplash source url).
      - Include an emoji icon for the profile picture/icon.
      - Layout: Cover -> Icon -> Title (Name) -> Properties (Tags) -> Content sections.
      - Return ONLY the raw HTML code, no markdown backticks.
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    let text = response.text || "";
    // Clean up markdown code blocks if present
    text = text.replace(/```html/g, '').replace(/```/g, '');
    return text;
  } catch (error) {
    console.error("Profile Gen Error:", error);
    throw error;
  }
};

/**
 * Rewrites text in a specific celebrity style.
 */
export const rewriteText = async (text: string, style: string): Promise<string> => {
  try {
    const prompt = `
      Rewrite the following text in the Vietnamese language, mimicking the style of: ${style}.
      
      Original Text:
      "${text}"
      
      Style Nuances:
      - Sơn Tùng M-TP: Abstract, sky, dreams, slightly arrogant but poetic, use words like "bầu trời", "cơn mưa".
      - Đen Vâu: Metaphorical, humble, rap lyrics flow, observational, daily life struggles, nature.
      - Thơ Xuân Quỳnh: Feminine, intense love, waves ("sóng"), traditional poetic structure, emotional.
      - Academic (Học thuật): Formal, complex vocabulary, structured, objective.
      - Romantic (Lãng mạn): Cheesy, emotional, flowery adjectives.
      
      Output only the rewritten text.
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    return response.text || "Could not generate text.";
  } catch (error) {
    console.error("Rewrite Error:", error);
    throw error;
  }
};
